services:
  plantuml-server:
    image: plantuml/plantuml-server:tomcat
    container_name: plantuml-server-html
    ports:
      - '8080:8080'
    networks:
      - umlnet

networks:
  umlnet:
    driver: bridge
