version: '3.8'

services:
  plantuml-server:
    image: plantuml/plantuml-server
    container_name: plantuml-server
    ports:
      - "8080:8080"
    networks:
      - umlnet

networks:
  umlnet:
    driver: bridge
